[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && yarn install"
]

[phases.build]
cmds = [
    "cd frontend && yarn build"
]

[start]
cmd = "cd backend && python start.py"
